---
# tasks file for epel
- include: RedHat-5.yml
  when: ansible_os_family == 'RedHat' and version_compare('5', '==')

- include: RedHat-6.yml
  when: ansible_os_family == 'RedHat' and version_compare('6', '==')
