---
- name: RedHat 6 | Create the repository for EPEL
  copy: src=epel-6.repo dest=/etc/yum.repos.d/epel.repo

- name: RedHat 6 | Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
